filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: booking-api
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              processors:
                - decode_json_fields:
                    fields: ["message"]
                    target: "app"
                    overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

logging.level: warning
